#### 查询数据格式  --超类

In [2]:
import numpy as np

In [3]:
ints = np.ones(10, dtype = np.uint16)
floats = np.ones(10, dtype = np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [4]:
np.issubdtype(floats.dtype, np.floating)

True

In [5]:
# 通过mro方法
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

### Numpy 高级数组操作

In [6]:
# 1 数组重塑 --reshape
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
arr.reshape((4, 2,)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
# 其中一维可以是-1，代表维度大小由数据本身推断
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
# shape本身也可以传入
other_arr = np.ones((3, 5))
other_arr.shape

(3, 5)

In [11]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
# 扁平化(flattening)/散开（raveling)  将多维数组转化为一维
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [14]:
arr.ravel()  # 扁平化操作 -- 不产生副本

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr.flatten()  # 产生副本

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### C和Fortran顺序  flags属性
C顺序：行优先，先经过更高的维度  
Fortran顺序：列优先，后经过更高的维度

In [19]:
arr = np.arange(12)
arr.reshape((4,3), order = "C")

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
arr.reshape((4,3), order = 'F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [21]:
# 合并
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.vstack((arr1,arr2))  # np.concatenate([arr1,arr2], axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
np.hstack((arr1,arr2))  # np.concatenate([arr1,arr2], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [23]:
# 沿指定轴在指定的位置拆分数组 --spilt
arr = np.random.randn(5,2)
arr

array([[ 0.67260805, -0.2166922 ],
       [ 0.57911471,  0.51135305],
       [ 0.14802112,  0.72588282],
       [-0.61302717,  1.99992279],
       [ 0.64071174, -0.63049059]])

In [26]:
first, second, third = np.split(arr, [1,3])
first

array([[ 0.67260805, -0.2166922 ]])

In [27]:
second

array([[ 0.57911471,  0.51135305],
       [ 0.14802112,  0.72588282]])

In [28]:
third

array([[-0.61302717,  1.99992279],
       [ 0.64071174, -0.63049059]])

In [30]:
# 堆叠辅助类   _c和_r
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = np.random.randn(3, 2)
np.r_[arr1,arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.45587374, -0.00543955],
       [-0.95734682, -0.89510738],
       [-1.40490775,  0.06978336]])

In [31]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        ,  0.45587374, -0.00543955],
       [ 2.        ,  3.        , -0.95734682, -0.89510738],
       [ 4.        ,  5.        , -1.40490775,  0.06978336]])

In [32]:
# 重复操作
# 1 repeat   --一个一个重复
arr = np.arange(3)
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [33]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [34]:
arr = np.random.randn(2,2)
arr

array([[ 0.22762744, -0.28691439],
       [-0.76314877,  0.61091258]])

In [35]:
arr.repeat(2, axis = 0)  # 按轴重复

array([[ 0.22762744, -0.28691439],
       [ 0.22762744, -0.28691439],
       [-0.76314877,  0.61091258],
       [-0.76314877,  0.61091258]])

In [36]:
# 2 tile    --一起重复
np.tile(arr, (2,1))  # (横向重复几遍，纵向重复几遍)

array([[ 0.22762744, -0.28691439],
       [-0.76314877,  0.61091258],
       [ 0.22762744, -0.28691439],
       [-0.76314877,  0.61091258]])

In [37]:
np.tile(arr, (3,2))

array([[ 0.22762744, -0.28691439,  0.22762744, -0.28691439],
       [-0.76314877,  0.61091258, -0.76314877,  0.61091258],
       [ 0.22762744, -0.28691439,  0.22762744, -0.28691439],
       [-0.76314877,  0.61091258, -0.76314877,  0.61091258],
       [ 0.22762744, -0.28691439,  0.22762744, -0.28691439],
       [-0.76314877,  0.61091258, -0.76314877,  0.61091258]])

In [38]:
# 花式索引
# take  --获取
# put  --设置
arr = np.arange(10)
inds = [7, 1, 2, 6]
arr[inds]

array([7, 1, 2, 6])

In [39]:
arr.take(inds)  # k可以使用axis

array([7, 1, 2, 6])

In [41]:
arr.put(inds, 42)  # 不接受axis传入，只可以扁平化C顺序
arr

array([ 0, 42, 42,  3,  4,  5, 42, 42,  8,  9])

In [42]:
arr = np.random.randn(1000, 50)
inds = np.random.permutation(1000)[:500]
%timeit arr[inds]

38.4 µs ± 4.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [43]:
%timeit arr.take(inds)  # 快得多

2.92 µs ± 354 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 广播 *broadcasting*
不同形状的数组之间的算数运算的执行方式  
用于传递的必须在传递轴是1吧。。

In [45]:
# np.newaxis
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape

(4, 1, 4)

### ufunc高级应用

In [47]:
# reduce 聚合
arr = np.arange(10)
np.add.reduce(arr)  # np.logical_and

45

In [50]:
# accumulate 过程累计
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis = 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [51]:
# outer 叉积
arr = np.arange(3).repeat([1, 2, 2])
arr

array([0, 1, 1, 2, 2])

In [52]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [53]:
result = np.subtract.outer(np.random.randn(3, 4), np.random.randn(5))
result.shape

(3, 4, 5)

In [ ]:
# 搞笑的降序 list[::-1]
# 间接排序： 单个  .argsort()
#           多个  .lexsort( , , )

In [ ]:
# 矩阵乘法
#  np.matrix()  直接*  xm.T * xm
#  求逆  xm.I